export { ReactComponent as FirstName } from "../Assets/Images/icon/firstname.svg";
export { ReactComponent as Phone } from "../Assets/Images/icon/phonenumber.svg";
export { ReactComponent as QuoteEnd } from "../Assets/Images/Effect-icons/quoteend.svg";
export { ReactComponent as Emailfold } from "../Assets/Images/icon/emailfold.svg";
export { ReactComponent as Menu } from "../Assets/Images/icon/Menu.svg";
export { ReactComponent as Close } from "../Assets/Images/icon/Close.svg";
export { ReactComponent as Featurecardimage1 } from "../Assets/Images/Effect-icons/featurecardimage1.svg";
export { ReactComponent as Featurecardimage2 } from "../Assets/Images/Effect-icons/featurecardimage2.svg";
export { ReactComponent as Featurecardimage3 } from "../Assets/Images/Effect-icons/featurecardimage3.svg"
export { ReactComponent as Featurecardimage4 } from "../Assets/Images/Effect-icons/featurecardimage4.svg";